# version: '3.8'
# services:
#   app:
#     user: www-data  # Add this line

#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: laravel10-php8.1
#     container_name: laravel10_app
#     restart: unless-stopped
#     tty: true
#     working_dir: /var/www
#     volumes:
#       - .:/var/www
#       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
#     ports:
#       - "8000:9000" 
#     networks:
#       - app-network

#   webserver:
#     image: webdevops/php-apache:8.1
#     container_name: apache
#     restart: unless-stopped
#     tty: true
#     working_dir: /var/www
#     volumes:
#       - .:/var/www
#       - ./apache/logs:/var/log/apache2 # Mount log directory

#       - ./apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
#     ports:
#       - "8080:80"
#     networks:
#       - app-network

#   db:
#     image: mysql:5.7
#     container_name: mysql
#     restart: unless-stopped
#     tty: true
#     ports:
#       - "3307:3306"
#     environment:
#       MYSQL_DATABASE: laravel
#       MYSQL_ROOT_PASSWORD: secret
#       MYSQL_USER: laravel
#       MYSQL_PASSWORD: secret
#     volumes:
#       - dbdata:/var/lib/mysql
#     networks:
#       - app-network

# volumes:
#   dbdata:
#     driver: local

# networks:
#   app-network:
#     driver: bridge



## nginx

version: '3.8'
services:
  app:
    user: www-data
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel10-php8.1
    container_name: laravel10_app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:9000"
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

volumes:
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge
